[general]
## Project name. This is a required field.
name = "misc-algos"

## Project version (in semver). This is a required field.
version = "0.6.2"

## Project authors.
authors = ["tttmmmyyyy"]

# description = "This is a Fix project."

license = "MIT"

[build]
files = [
    "zp.fix",
    "combinatorics.fix",
    "traits.fix",
    "geometry.fix",
    "graph.fix",
    "functional.fix",
]

[build.test]
files = [
    "test.fix",
    "zp-test.fix",
    "combinatorics-test.fix",
    "graph-test.fix",
    "geometry-test.fix",
]
# memcheck = true

## By "[[dependencies]]" array, you can specify a Fix project as a dependency.
## Each dependent project must have "fixproj.toml" file at the project root directory.
## If a dependent project also has dependencies, "fix" will consider them recursively.
## NOTE: The syntax for version requirement is the same as in Cargo. See: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

## The following is an example of a dependency to a project in the local file system.
# [[dependencies]]
# name = "another-project"
# version = "*"
# path = "/path/to/project"

## The following is an example of a dependency to a project in a remote git repository.
## In this case, "fix" searches the tags (each name should be a semver, or semver with "v" prefix) of the repository to find the version that satisfies the requirement.
## If the repository has no tags, "fix" will use the latest commit of the default branch.
# [[dependencies]]
# name = "your-project"
# version = "1.2.0"
# git = { url = "https://github.com/tttmmmyyyy/your-project.git" }

[[dependencies]]
name = "math"
version = "1.0.0"
git = { url = "https://github.com/tttmmmyyyy/fixlang-math.git" }


[[dependencies]]
name = "binary-heap"
version = "0.1.0"
git = { url = "https://github.com/tttmmmyyyy/fixlang-binary-heap.git" }
